on:
  push:
    branches:
      - main
      - test
jobs:
  container:
    runs-on: ubuntu-latest
    container: ubuntu:22.04
    steps:
      - run: apt update
      - run: apt upgrade
      - run: apt install python3 && apt install git
      - run: git checkout https://github.com/FatConan/sand.git
      - run: pip install sand/
      - run: sand .
